//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverythingToolbar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EverythingToolbar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string AboutLicense {
            get {
                return ResourceManager.GetString("AboutLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string AboutOK {
            get {
                return ResourceManager.GetString("AboutOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string AboutWebsite {
            get {
                return ResourceManager.GetString("AboutWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About EverythingToolbar.
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string ContextMenuCopy {
            get {
                return ResourceManager.GetString("ContextMenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string ContextMenuCopyFile {
            get {
                return ResourceManager.GetString("ContextMenuCopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Full Name to Clipboard.
        /// </summary>
        public static string ContextMenuCopyFullName {
            get {
                return ResourceManager.GetString("ContextMenuCopyFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string ContextMenuCut {
            get {
                return ResourceManager.GetString("ContextMenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ContextMenuOpen {
            get {
                return ResourceManager.GetString("ContextMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Path.
        /// </summary>
        public static string ContextMenuOpenPath {
            get {
                return ResourceManager.GetString("ContextMenuOpenPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more options.
        /// </summary>
        public static string ContextMenuOpenWinContext {
            get {
                return ResourceManager.GetString("ContextMenuOpenWinContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with....
        /// </summary>
        public static string ContextMenuOpenWith {
            get {
                return ResourceManager.GetString("ContextMenuOpenWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose app.
        /// </summary>
        public static string ContextMenuOpenWithChooseApp {
            get {
                return ResourceManager.GetString("ContextMenuOpenWithChooseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rules defined.
        /// </summary>
        public static string ContextMenuOpenWithNoRules {
            get {
                return ResourceManager.GetString("ContextMenuOpenWithNoRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string ContextMenuPaste {
            get {
                return ResourceManager.GetString("ContextMenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string ContextMenuProperties {
            get {
                return ResourceManager.GetString("ContextMenuProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as admin.
        /// </summary>
        public static string ContextMenuRunAsAdmin {
            get {
                return ResourceManager.GetString("ContextMenuRunAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Everything.
        /// </summary>
        public static string ContextMenuShowInEverything {
            get {
                return ResourceManager.GetString("ContextMenuShowInEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string DefaultFilterAll {
            get {
                return ResourceManager.GetString("DefaultFilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string DefaultFilterFile {
            get {
                return ResourceManager.GetString("DefaultFilterFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string DefaultFilterFolder {
            get {
                return ResourceManager.GetString("DefaultFilterFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact.
        /// </summary>
        public static string ItemTemplateCompact {
            get {
                return ResourceManager.GetString("ItemTemplateCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact (detailed).
        /// </summary>
        public static string ItemTemplateCompactDetailed {
            get {
                return ResourceManager.GetString("ItemTemplateCompactDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string ItemTemplateNormal {
            get {
                return ResourceManager.GetString("ItemTemplateNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal (detailed).
        /// </summary>
        public static string ItemTemplateNormalDetailed {
            get {
                return ResourceManager.GetString("ItemTemplateNormalDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt.
        /// </summary>
        public static string KeyAlt {
            get {
                return ResourceManager.GetString("KeyAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl.
        /// </summary>
        public static string KeyCtrl {
            get {
                return ResourceManager.GetString("KeyCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string KeyShift {
            get {
                return ResourceManager.GetString("KeyShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win.
        /// </summary>
        public static string KeyWin {
            get {
                return ResourceManager.GetString("KeyWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to copy the exception content to clipboard?.
        /// </summary>
        public static string MessageBoxCopyException {
            get {
                return ResourceManager.GetString("MessageBoxCopyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy file..
        /// </summary>
        public static string MessageBoxFailedToCopyFile {
            get {
                return ResourceManager.GetString("MessageBoxFailedToCopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy path..
        /// </summary>
        public static string MessageBoxFailedToCopyPath {
            get {
                return ResourceManager.GetString("MessageBoxFailedToCopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open search result..
        /// </summary>
        public static string MessageBoxFailedToOpen {
            get {
                return ResourceManager.GetString("MessageBoxFailedToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open dialog..
        /// </summary>
        public static string MessageBoxFailedToOpenDialog {
            get {
                return ResourceManager.GetString("MessageBoxFailedToOpenDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open path..
        /// </summary>
        public static string MessageBoxFailedToOpenPath {
            get {
                return ResourceManager.GetString("MessageBoxFailedToOpenPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register hotkey. It might be in use by another application..
        /// </summary>
        public static string MessageBoxFailedToRegisterHotkey {
            get {
                return ResourceManager.GetString("MessageBoxFailedToRegisterHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to run command.
        /// </summary>
        public static string MessageBoxFailedToRunCommand {
            get {
                return ResourceManager.GetString("MessageBoxFailedToRunCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To utilize this sorting method it has to have fast sorting enabled. It can be enabled in your Everything settings..
        /// </summary>
        public static string MessageBoxFastSortUnavailable {
            get {
                return ResourceManager.GetString("MessageBoxFastSortUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast sorting not enabled.
        /// </summary>
        public static string MessageBoxFastSortUnavailableTitle {
            get {
                return ResourceManager.GetString("MessageBoxFastSortUnavailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one regular expression is invalid..
        /// </summary>
        public static string MessageBoxRegExInvalid {
            get {
                return ResourceManager.GetString("MessageBoxRegExInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule names cannot be empty..
        /// </summary>
        public static string MessageBoxRuleNameEmpty {
            get {
                return ResourceManager.GetString("MessageBoxRuleNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Everything.exe....
        /// </summary>
        public static string MessageBoxSelectEverythingExe {
            get {
                return ResourceManager.GetString("MessageBoxSelectEverythingExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Filters.csv file. By default it can be found in %APPDATA%\Everything. Its location might be different depending on your installation. If the file does not exist for you that means you didn&apos;t perform any changes to Everything&apos;s default filters..
        /// </summary>
        public static string MessageBoxSelectFiltersCsv {
            get {
                return ResourceManager.GetString("MessageBoxSelectFiltersCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.csv not found.
        /// </summary>
        public static string MessageBoxSelectFiltersCsvTitle {
            get {
                return ResourceManager.GetString("MessageBoxSelectFiltersCsvTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occured.
        /// </summary>
        public static string MessageBoxUnhandledExceptionTitle {
            get {
                return ResourceManager.GetString("MessageBoxUnhandledExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically apply rules based on condition.
        /// </summary>
        public static string RulesAutoApply {
            get {
                return ResourceManager.GetString("RulesAutoApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string RulesCancel {
            get {
                return ResourceManager.GetString("RulesCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string RulesCommand {
            get {
                return ResourceManager.GetString("RulesCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string RulesName {
            get {
                return ResourceManager.GetString("RulesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Expression.
        /// </summary>
        public static string RulesRegularExpression {
            get {
                return ResourceManager.GetString("RulesRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string RulesSave {
            get {
                return ResourceManager.GetString("RulesSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string RulesType {
            get {
                return ResourceManager.GetString("RulesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use %file%, %filename% and %path% as placeholders in commands..
        /// </summary>
        public static string RulesWindowText {
            get {
                return ResourceManager.GetString("RulesWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string RulesWindowTitle {
            get {
                return ResourceManager.GetString("RulesWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objects.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About EverythingToolbar....
        /// </summary>
        public static string SettingsAbout {
            get {
                return ResourceManager.GetString("SettingsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Shortcut....
        /// </summary>
        public static string SettingsChangeShortcut {
            get {
                return ResourceManager.GetString("SettingsChangeShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates automatically.
        /// </summary>
        public static string SettingsCheckForUpdates {
            get {
                return ResourceManager.GetString("SettingsCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable animations.
        /// </summary>
        public static string SettingsDisableAnimations {
            get {
                return ResourceManager.GetString("SettingsDisableAnimations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click to open.
        /// </summary>
        public static string SettingsDoubleClickToOpen {
            get {
                return ResourceManager.GetString("SettingsDoubleClickToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable search history.
        /// </summary>
        public static string SettingsEnableHistory {
            get {
                return ResourceManager.GetString("SettingsEnableHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide empty search.
        /// </summary>
        public static string SettingsHideEmptyResults {
            get {
                return ResourceManager.GetString("SettingsHideEmptyResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Case.
        /// </summary>
        public static string SettingsMatchCase {
            get {
                return ResourceManager.GetString("SettingsMatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Path.
        /// </summary>
        public static string SettingsMatchPath {
            get {
                return ResourceManager.GetString("SettingsMatchPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Whole Word.
        /// </summary>
        public static string SettingsMatchWholeWord {
            get {
                return ResourceManager.GetString("SettingsMatchWholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string SettingsPreferences {
            get {
                return ResourceManager.GetString("SettingsPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Expressions.
        /// </summary>
        public static string SettingsRegularExpressions {
            get {
                return ResourceManager.GetString("SettingsRegularExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember filter.
        /// </summary>
        public static string SettingsRememberFilter {
            get {
                return ResourceManager.GetString("SettingsRememberFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace start menu search (experimental).
        /// </summary>
        public static string SettingsReplaceStartMenuSearch {
            get {
                return ResourceManager.GetString("SettingsReplaceStartMenuSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules....
        /// </summary>
        public static string SettingsRules {
            get {
                return ResourceManager.GetString("SettingsRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search as you type.
        /// </summary>
        public static string SettingsSearchAsYouType {
            get {
                return ResourceManager.GetString("SettingsSearchAsYouType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select first result.
        /// </summary>
        public static string SettingsSelectFirstResult {
            get {
                return ResourceManager.GetString("SettingsSelectFirstResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set instance name....
        /// </summary>
        public static string SettingsSetInstanceName {
            get {
                return ResourceManager.GetString("SettingsSetInstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show quick toggles.
        /// </summary>
        public static string SettingsShowQuickToggles {
            get {
                return ResourceManager.GetString("SettingsShowQuickToggles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show results count.
        /// </summary>
        public static string SettingsShowResultsCount {
            get {
                return ResourceManager.GetString("SettingsShowResultsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        public static string SettingsSortBy {
            get {
                return ResourceManager.GetString("SettingsSortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string SettingsTheme {
            get {
                return ResourceManager.GetString("SettingsTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync theme.
        /// </summary>
        public static string SettingsThemeAuto {
            get {
                return ResourceManager.GetString("SettingsThemeAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable thumbnails.
        /// </summary>
        public static string SettingsThumbnailsEnabled {
            get {
                return ResourceManager.GetString("SettingsThumbnailsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Everything filters.
        /// </summary>
        public static string SettingsUseEverythingFilters {
            get {
                return ResourceManager.GetString("SettingsUseEverythingFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string SettingsView {
            get {
                return ResourceManager.GetString("SettingsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ShortcutOK {
            get {
                return ResourceManager.GetString("ShortcutOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter shortcut....
        /// </summary>
        public static string ShortcutWindowTitle {
            get {
                return ResourceManager.GetString("ShortcutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string SortAscending {
            get {
                return ResourceManager.GetString("SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string SortByAttributes {
            get {
                return ResourceManager.GetString("SortByAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date accessed.
        /// </summary>
        public static string SortByDateAccessed {
            get {
                return ResourceManager.GetString("SortByDateAccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        public static string SortByDateCreated {
            get {
                return ResourceManager.GetString("SortByDateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date modified.
        /// </summary>
        public static string SortByDateModified {
            get {
                return ResourceManager.GetString("SortByDateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date recently changed.
        /// </summary>
        public static string SortByDateRecentlyChanged {
            get {
                return ResourceManager.GetString("SortByDateRecentlyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date run.
        /// </summary>
        public static string SortByDateRun {
            get {
                return ResourceManager.GetString("SortByDateRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string SortByExtension {
            get {
                return ResourceManager.GetString("SortByExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File list filename.
        /// </summary>
        public static string SortByFileListFilename {
            get {
                return ResourceManager.GetString("SortByFileListFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SortByName {
            get {
                return ResourceManager.GetString("SortByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string SortByPath {
            get {
                return ResourceManager.GetString("SortByPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run count.
        /// </summary>
        public static string SortByRunCount {
            get {
                return ResourceManager.GetString("SortByRunCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string SortBySize {
            get {
                return ResourceManager.GetString("SortBySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name.
        /// </summary>
        public static string SortByTypeName {
            get {
                return ResourceManager.GetString("SortByTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string SortDescending {
            get {
                return ResourceManager.GetString("SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search with Everything.
        /// </summary>
        public static string TextBoxWatermark {
            get {
                return ResourceManager.GetString("TextBoxWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string UpdateBannerDownload {
            get {
                return ResourceManager.GetString("UpdateBannerDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string UpdateBannerSkip {
            get {
                return ResourceManager.GetString("UpdateBannerSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available:.
        /// </summary>
        public static string UpdateBannerText {
            get {
                return ResourceManager.GetString("UpdateBannerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string UserFilterAudio {
            get {
                return ResourceManager.GetString("UserFilterAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressed.
        /// </summary>
        public static string UserFilterCompressed {
            get {
                return ResourceManager.GetString("UserFilterCompressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string UserFilterDocument {
            get {
                return ResourceManager.GetString("UserFilterDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable.
        /// </summary>
        public static string UserFilterExecutable {
            get {
                return ResourceManager.GetString("UserFilterExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string UserFilterPicture {
            get {
                return ResourceManager.GetString("UserFilterPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string UserFilterPlaceholder {
            get {
                return ResourceManager.GetString("UserFilterPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string UserFilterVideo {
            get {
                return ResourceManager.GetString("UserFilterVideo", resourceCulture);
            }
        }
    }
}
