<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <SupportedOSPlatform>windows</SupportedOSPlatform>
    <OutputType>Library</OutputType>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
    <Platforms>x64;ARM64</Platforms>
    <RootNamespace>EverythingToolbar</RootNamespace>
  </PropertyGroup>
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyOriginatorKeyFile>..\EverythingToolbar.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
</Project>
