name: Bug report
description: Create a bug report
body:
- type: checkboxes
  attributes:
    label: Preflight Checklist
    description: Please ensure you've completed all of the following.
    options:
      - label: I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/develop/README.md) and it did not solve the problem.
        required: true
      - label: I have read the [FAQ](https://github.com/srwi/EverythingToolbar/blob/develop/FAQ.md) and it did not solve the problem.
        required: true
      - label: I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.
        required: true
- id: version
  type: input
  attributes:
    label: EverythingToolbar Version
    description: What version of EverythingToolbar are you using?
    placeholder: "e.g. 2.0.0"
  validations:
    required: true
- type: dropdown
  id: variant
  attributes:
    label: Variant
    description: What variant of EverythingToolbar are you using? [What are the different variants?](https://github.com/srwi/EverythingToolbar/blob/develop/FAQ.md#-what-is-the-difference-between-the-deskband-and-launcher-variants-of-everythingtoolbar)
    options:
      - Not applicable / Don't know
      - Taskbar search box / Launcher
      - Search icon / Launcher
      - Deskband
  validations:
    required: true
- id: et_version
  type: input
  attributes:
    label: Everything Version
    description: What version of Everything are you using?
    placeholder: "e.g. 1.4.1.1024 (x64)"
  validations:
    required: true
- id: windows_version
  type: input
  attributes:
    label: Windows Version
    description: What Windows version are you using? Click Start button > Settings > System > About.
    placeholder: "e.g. Windows 11 24H2"
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: Describe exactly how to reproduce the behaviour.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual Behavior
    description: A clear description of what actually happens.
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help explain your problem. You can simply drag and drop any image file into the editor to add it to the report.
- type: textarea
  attributes:
    label: Log output
    description: To copy the log file output press <kbd>Win</kbd>+<kbd>R</kbd>, run `%TEMP%\EverythingToolbar.log` and paste the file content below. Please provide the log file even if you think it does not contain relevant information.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Information
    description: Are there any other details that may be relevant to the issue like unusual system configurations or third party software that may be involved?
- type: checkboxes
  id: ensure_effort
  attributes:
    label: Final Checklist
    description: Before submitting, please confirm the following to help provide better support.
    options:
      - label: I have provided detailed, clear information in all required fields above and put genuine effort into this bug report.
        required: true