//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverythingToolbar.Launcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EverythingToolbar.Launcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string ContextMenuQuit {
            get {
                return ResourceManager.GetString("ContextMenuQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run setup assistant....
        /// </summary>
        public static string ContextMenuRunSetupAssistant {
            get {
                return ResourceManager.GetString("ContextMenuRunSetupAssistant", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        public static string ContextMenuSettings {
            get {
                return ResourceManager.GetString("ContextMenuSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit the setup assistant? EverythingToolbar will only be accessible using the keyboard shortcut. You can access the setup assistant again via the system tray icon to pin the search icon to the taskbar..
        /// </summary>
        public static string SetupAssistantDisableWarningText {
            get {
                return ResourceManager.GetString("SetupAssistantDisableWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Setup Assistant.
        /// </summary>
        public static string SetupAssistantDisableWarningTitle {
            get {
                return ResourceManager.GetString("SetupAssistantDisableWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string SetupAssistantDone {
            get {
                return ResourceManager.GetString("SetupAssistantDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable autostart.
        /// </summary>
        public static string SetupAssistantEnableAutostart {
            get {
                return ResourceManager.GetString("SetupAssistantEnableAutostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically starts EverythingToolbar when Windows starts.
        /// </summary>
        public static string SetupAssistantEnableAutostartHelp {
            get {
                return ResourceManager.GetString("SetupAssistantEnableAutostartHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable system tray icon.
        /// </summary>
        public static string SetupAssistantEnableSystemTray {
            get {
                return ResourceManager.GetString("SetupAssistantEnableSystemTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables the system tray icon for quick access to settings.
        /// </summary>
        public static string SetupAssistantEnableSystemTrayHelp {
            get {
                return ResourceManager.GetString("SetupAssistantEnableSystemTrayHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show search box on the taskbar.
        /// </summary>
        public static string SetupAssistantTaskbarWindow {
            get {
                return ResourceManager.GetString("SetupAssistantTaskbarWindow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adds an Everything search box directly to the Windows 11 taskbar.
        /// </summary>
        public static string SetupAssistantTaskbarWindowHelp {
            get {
                return ResourceManager.GetString("SetupAssistantTaskbarWindowHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hide Windows search icon.
        /// </summary>
        public static string SetupAssistantHideWindowsSearch {
            get {
                return ResourceManager.GetString("SetupAssistantHideWindowsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hides the original Windows search icon from the taskbar.
        /// </summary>
        public static string SetupAssistantHideWindowsSearchHelp {
            get {
                return ResourceManager.GetString("SetupAssistantHideWindowsSearchHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin to taskbar.
        /// </summary>
        public static string SetupAssistantPinToTaskbar {
            get {
                return ResourceManager.GetString("SetupAssistantPinToTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To pin EverythingToolbar to the taskbar right click its icon and select &apos;Pin to taskbar&apos;..
        /// </summary>
        public static string SetupAssistantPinToTaskbarHelp {
            get {
                return ResourceManager.GetString("SetupAssistantPinToTaskbarHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string SetupAssistantPreferences {
            get {
                return ResourceManager.GetString("SetupAssistantPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An explorer restart is required to update the taskbar icon. Would you like to restart it now?.
        /// </summary>
        public static string SetupAssistantRestartExplorerDialogText {
            get {
                return ResourceManager.GetString("SetupAssistantRestartExplorerDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart explorer.
        /// </summary>
        public static string SetupAssistantRestartExplorerDialogTitle {
            get {
                return ResourceManager.GetString("SetupAssistantRestartExplorerDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EverythingToolbar Setup Assistant.
        /// </summary>
        public static string SetupAssistantTitle {
            get {
                return ResourceManager.GetString("SetupAssistantTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system tray icon cannot be disabled when EverythingToolbar is not pinned to the taskbar. Please pin EverythingToolbar to the taskbar first, or keep the system tray icon enabled to access settings and functionality..
        /// </summary>
        public static string TrayIconDisableErrorText {
            get {
                return ResourceManager.GetString("TrayIconDisableErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot disable system tray icon.
        /// </summary>
        public static string TrayIconDisableErrorTitle {
            get {
                return ResourceManager.GetString("TrayIconDisableErrorTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The tray icon has been enabled so that EverythingToolbar remains accessible, because the taskbar icon is not pinned..
        /// </summary>
        public static string TaskbarWindowDisabledTrayEnabledText {
            get {
                return ResourceManager.GetString("TaskbarWindowDisabledTrayEnabledText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tray icon enabled.
        /// </summary>
        public static string TaskbarWindowDisabledTrayEnabledTitle {
            get {
                return ResourceManager.GetString("TaskbarWindowDisabledTrayEnabledTitle", resourceCulture);
            }
        }
    }
}
