//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverythingToolbar.Launcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EverythingToolbar.Launcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string CheckboxEnable {
            get {
                return ResourceManager.GetString("CheckboxEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string CheckboxHide {
            get {
                return ResourceManager.GetString("CheckboxHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string ContextMenuQuit {
            get {
                return ResourceManager.GetString("ContextMenuQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run setup assistant....
        /// </summary>
        public static string ContextMenuRunSetupAssistant {
            get {
                return ResourceManager.GetString("ContextMenuRunSetupAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit the setup assistant? EverythingToolbar will only be accessible using the keyboard shortcut. You can access the setup assistant again via the system tray icon to pin the search icon to the taskbar..
        /// </summary>
        public static string SetupAssistantDisableWarningText {
            get {
                return ResourceManager.GetString("SetupAssistantDisableWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Setup Assistant.
        /// </summary>
        public static string SetupAssistantDisableWarningTitle {
            get {
                return ResourceManager.GetString("SetupAssistantDisableWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By enabling the system tray icon you can quit the EverythingToolbar background process at any time. Without it, EverythingToolbar can always be quit via the task manager..
        /// </summary>
        public static string SetupAssistantFifthStepText {
            get {
                return ResourceManager.GetString("SetupAssistantFifthStepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Configure system tray icon.
        /// </summary>
        public static string SetupAssistantFifthStepTitle {
            get {
                return ResourceManager.GetString("SetupAssistantFifthStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one of the following taskbar icons:.
        /// </summary>
        public static string SetupAssistantFirstStepText {
            get {
                return ResourceManager.GetString("SetupAssistantFirstStepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Taskbar icon.
        /// </summary>
        public static string SetupAssistantFirstStepTitle {
            get {
                return ResourceManager.GetString("SetupAssistantFirstStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is recommended to start EverythingToolbar automatically on system startup..
        /// </summary>
        public static string SetupAssistantFourthStepText {
            get {
                return ResourceManager.GetString("SetupAssistantFourthStepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Configure autostart.
        /// </summary>
        public static string SetupAssistantFourthStepTitle {
            get {
                return ResourceManager.GetString("SetupAssistantFourthStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An explorer restart is required to update the taskbar icon. Would you like to restart it now?.
        /// </summary>
        public static string SetupAssistantRestartExplorerDialogText {
            get {
                return ResourceManager.GetString("SetupAssistantRestartExplorerDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart explorer.
        /// </summary>
        public static string SetupAssistantRestartExplorerDialogTitle {
            get {
                return ResourceManager.GetString("SetupAssistantRestartExplorerDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To pin EverythingToolbar to the taskbar right click its icon and select &apos;Pin to taskbar&apos;..
        /// </summary>
        public static string SetupAssistantSecondStepText {
            get {
                return ResourceManager.GetString("SetupAssistantSecondStepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Pin to taskbar.
        /// </summary>
        public static string SetupAssistantSecondStepTitle {
            get {
                return ResourceManager.GetString("SetupAssistantSecondStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionally the original Windows search icon can be hidden..
        /// </summary>
        public static string SetupAssistantThirdStepText {
            get {
                return ResourceManager.GetString("SetupAssistantThirdStepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Hide Windows search.
        /// </summary>
        public static string SetupAssistantThirdStepTitle {
            get {
                return ResourceManager.GetString("SetupAssistantThirdStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EverythingToolbar Setup Assistant.
        /// </summary>
        public static string SetupAssistantTitle {
            get {
                return ResourceManager.GetString("SetupAssistantTitle", resourceCulture);
            }
        }
    }
}
