name: Publish to WinGet

on:
  release:
    types: [released]
  workflow_dispatch: 
      inputs:
        version_tag:
          description: 'Tag to run winget-releaser for'
          required: true

permissions:
  contents: read

jobs:
  winget:
    name: Publish to WinGet
    runs-on: ubuntu-latest
    steps:
      - name: Sync winget-pkgs fork
        run: gh repo sync srwi/winget-pkgs -b master
        env:
          GH_TOKEN: ${{ secrets.WINGET_PAT }}
      - name: Update Launcher
        uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: srwi.EverythingToolbar.Launcher
          token: ${{ secrets.WINGET_PAT }}
          installers-regex: '-x64\.exe$|-arm64\.exe$'
          release-tag: ${{ inputs.version_tag || github.event.release.tag_name }}
      - name: Update Deskband
        uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: srwi.EverythingToolbar.Deskband
          token: ${{ secrets.WINGET_PAT }}
          installers-regex: '-x64\.exe$|-arm64\.exe$'
          release-tag: ${{ inputs.version_tag || github.event.release.tag_name }}
